In [89]:
from pyunicorn.timeseries.surrogates import Surrogates
import numpy as np
from scipy.stats import norm

In [63]:
data = np.load('data.npy')

In [65]:
result = []

for i in range(data.shape[0]):
    for j in range(data.shape[1]):
        if not data[i,j,-1]<0:
            result.append(data[i,j,:])


In [69]:
data = np.matrix(result)

In [99]:
N = 100
M = data.shape[0]
result = np.zeros((N,M))
for i in range(N):
    ts = Surrogates(data)
    sample = ts.correlated_noise_surrogates(data)
    eigenValues, eigenVectors = np.linalg.eig(np.cov(sample))
    idx = eigenValues.argsort()[::-1]   
    eigenValues = eigenValues[idx]
    result[i,:] = eigenValues
    ts.clear_cache()

Generated an instance of the Surrogates class.
Generating correlated noise surrogates...
Generated an instance of the Surrogates class.
Generating correlated noise surrogates...
Generated an instance of the Surrogates class.
Generating correlated noise surrogates...
Generated an instance of the Surrogates class.
Generating correlated noise surrogates...
Generated an instance of the Surrogates class.
Generating correlated noise surrogates...
Generated an instance of the Surrogates class.
Generating correlated noise surrogates...
Generated an instance of the Surrogates class.
Generating correlated noise surrogates...
Generated an instance of the Surrogates class.
Generating correlated noise surrogates...
Generated an instance of the Surrogates class.
Generating correlated noise surrogates...
Generated an instance of the Surrogates class.
Generating correlated noise surrogates...
Generated an instance of the Surrogates class.
Generating correlated noise surrogates...
Generated an instance

Generated an instance of the Surrogates class.
Generating correlated noise surrogates...
Generated an instance of the Surrogates class.
Generating correlated noise surrogates...
Generated an instance of the Surrogates class.
Generating correlated noise surrogates...
Generated an instance of the Surrogates class.
Generating correlated noise surrogates...
Generated an instance of the Surrogates class.
Generating correlated noise surrogates...
Generated an instance of the Surrogates class.
Generating correlated noise surrogates...
Generated an instance of the Surrogates class.
Generating correlated noise surrogates...


In [100]:
eigenValues, eigenVectors = np.linalg.eig(np.cov(data))
idx = eigenValues.argsort()[::-1]   
eigenValues = eigenValues[idx]

In [103]:
norm.cdf(2)

0.9772498680518208

In [101]:
for i in range(N):
    print("%f"%(1 - norm.cdf((eigenValues[i] - result[i,:].mean())/result[i,:].std())))

0.000000
0.000000
0.004731
0.041116
0.119569
0.198830
0.243543
0.257473
0.288882
0.306030
0.321041
0.339405
0.346280
0.380963
0.393959
0.398749
0.404178
0.409623
0.429249
0.437046
0.438979
0.447201
0.452259
0.456054
0.459150
0.461932
0.466221
0.470326
0.473220
0.474580
0.477175
0.481162
0.482885
0.485857
0.488400
0.489398
0.491075
0.492880
0.494011
0.496742
0.497551
0.499745
0.501655
0.502370
0.503688
0.504840
0.505774
0.506189
0.507526
0.508716
0.509326
0.511003
0.511297
0.512244
0.512432
0.513463
0.513758
0.514470
0.515324
0.515715
0.516121
0.516666
0.517599
0.518564
0.519004
0.519460
0.519599
0.519946
0.520365
0.520776
0.521044
0.521496
0.521762
0.522275
0.522688
0.522688
0.522870
0.523165
0.523691
0.524018
0.524237
0.524257
0.524810
0.524706
0.525034
0.525201
0.525474
0.525689
0.525937
0.526121
0.526283
0.526333
0.526694
0.526864
0.526701
0.527155
0.527142
0.527994
0.528200
0.528210


In [34]:
d = np.row_stack((a,b,c))

In [48]:
ts = Surrogates(d)

Generated an instance of the Surrogates class.


In [47]:
ts.AAFT_surrogates(d)

Generating correlated noise surrogates...


AttributeError: 'Surrogates' object has no attribute '_original_data_fft'

Generating correlated noise surrogates...


array([[ 3.9791028 ,  5.45287519,  5.02532696,  1.94243231,  1.3774935 ,
         3.02007958,  1.86420421,  3.7646391 ],
       [ 4.22527408,  2.90988095,  7.94998781,  3.50909721, -2.71409865,
         4.7119573 ,  4.94455026,  4.76008565],
       [-3.59516812, -1.97702414, -6.70089651, -6.96161177, -6.30666783,
        -5.75830119, -4.50530105, -3.28342285]])

In [39]:
ts.white_noise_surrogates(d)

Generating white noise surrogates by random shuffling...


array([[ 3,  5,  5,  1,  3,  5,  4,  2],
       [ 8, 12,  7,  6,  5,  3,  3,  4],
       [ 2,  7,  6,  7,  5,  4,  6,  3]])

In [45]:
ts.refined_AAFT_surrogates(d,1000)

AttributeError: 'Surrogates' object has no attribute '_original_data_fft'

In [58]:
N = 10
result = np.zeros((N,3))
for i in range(N):
    ts = Surrogates(d)
    sample = ts.correlated_noise_surrogates(d)
    eigenValues, eigenVectors = np.linalg.eig(np.cov(sample))
    idx = eigenValues.argsort()[::-1]   
    eigenValues = eigenValues[idx]
    result[i,:] = eigenValues
    ts.clear_cache()

Generated an instance of the Surrogates class.
Generating correlated noise surrogates...
Generated an instance of the Surrogates class.
Generating correlated noise surrogates...
Generated an instance of the Surrogates class.
Generating correlated noise surrogates...
Generated an instance of the Surrogates class.
Generating correlated noise surrogates...
Generated an instance of the Surrogates class.
Generating correlated noise surrogates...
Generated an instance of the Surrogates class.
Generating correlated noise surrogates...
Generated an instance of the Surrogates class.
Generating correlated noise surrogates...
Generated an instance of the Surrogates class.
Generating correlated noise surrogates...
Generated an instance of the Surrogates class.
Generating correlated noise surrogates...
Generated an instance of the Surrogates class.
Generating correlated noise surrogates...


In [50]:
np.cov(d)

array([[ 2.28571429, -1.28571429,  2.71428571],
       [-1.28571429,  9.14285714, -1.        ],
       [ 2.71428571, -1.        ,  3.42857143]])

In [51]:
d

array([[ 1,  2,  3,  3,  4,  5,  5,  5],
       [12,  3,  4,  5,  6,  7,  3,  8],
       [ 2,  3,  4,  5,  6,  7,  6,  7]])

In [60]:
eigenValues, eigenVectors = np.linalg.eig(np.cov(d))
idx = eigenValues.argsort()[::-1]   
eigenValues = eigenValues[idx]

In [59]:
result

array([[ 9.90562985,  3.93204551,  0.82269823],
       [10.91110084,  2.33278413,  1.31345101],
       [11.46662559,  2.34593331,  0.78591232],
       [10.25746858,  3.63521738,  0.62321524],
       [11.58200185,  2.7306186 ,  0.15794229],
       [ 9.92805697,  3.51538064,  1.12691524],
       [10.02253596,  3.37299933,  1.38606517],
       [ 9.21170952,  4.57287297,  0.99065836],
       [10.01374339,  4.10176874,  0.3919988 ],
       [10.86831356,  3.15128156,  0.55702729]])

In [61]:
eigenValues

array([9.76570372, 5.02381354, 0.06762559])